### ISSUE TITLE
Setting MaxAge to 0 doesn't seem to work

### ISSUE THREAD

**Issue by chabber** [winebarrel/redash-go#136]
When settint MaxAge = 0 on the input, it is still trying to run a cached query.  Below is my code: 

```
	input := redash.ExecQueryJSONInput{
		Parameters: map[string]any{"external_id": id},
		MaxAge:     0,
	}
```

When I run it in debug mode, I can see the parameter being passed, but not the max_age setting.  From debug output:

---request begin---
POST /api/queries/333/results HTTP/1.1
Host: [redacted]
Authorization: Key [redacted]
Content-Type: application/json
User-Agent: redash-go

{"parameters":{"external_id":"org_9XpkEHv6XcpRCC"}}
---request end---

**Comment by winebarrel** [comment]
Thank you for your report.
I'm currently investigating, but it doesn't work when I pass max_age=0, so I'm looking into the cause.

```
worker-1     | [2024-06-09 05:16:41,925][PID:73][ERROR][rq.worker] [Job 469a2138-882b-40f7-b3f4-7e4d07d6859e]: exception raised while executing (redash.tasks.queries.execution.execute_query)
worker-1     | Traceback (most recent call last):
worker-1     |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job
worker-1     |     rv = job.perform()
worker-1     |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform
worker-1     |     self._result = self._execute()
worker-1     |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute
worker-1     |     result = self.func(*self.args, **self.kwargs)
worker-1     |   File "/app/redash/tasks/queries/execution.py", line 276, in execute_query
worker-1     |     return QueryExecutor(
worker-1     |   File "/app/redash/tasks/queries/execution.py", line 176, in run
worker-1     |     self._log_progress("executing_query")
worker-1     |   File "/app/redash/tasks/queries/execution.py", line 252, in _log_progress
worker-1     |     self.data_source.type,
worker-1     | AttributeError: 'NoneType' object has no attribute 'type'
```

Sorry, it will take some time to fix it.

**Comment by winebarrel** [comment]
Supported max_age=0 in v2.2.0.
https://pkg.go.dev/github.com/winebarrel/redash-go/v2@v2.2.0

Please be careful as `Test_ExecQueryJSON()` will not return results if you set `max_age=0`.
see https://github.com/winebarrel/redash-go?tab=readme-ov-file#max_age0
